# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MazeGui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mazeMenu(object):
    def setupUi(self, mazeMenu):
        mazeMenu.setObjectName("mazeMenu")
        mazeMenu.resize(690, 520)
        mazeMenu.setMinimumSize(QtCore.QSize(690, 520))
        mazeMenu.setAutoFillBackground(False)
        self.frame = QtWidgets.QFrame(mazeMenu)
        self.frame.setGeometry(QtCore.QRect(10, 10, 500, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(mazeMenu)
        self.frame_2.setGeometry(QtCore.QRect(520, 10, 160, 500))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.drawButton = QtWidgets.QPushButton(self.frame_2)
        self.drawButton.setGeometry(QtCore.QRect(10, 470, 141, 20))
        self.drawButton.setObjectName("drawButton")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 10, 141, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 129, 89))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.nXLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.nXLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.nXLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.nXLabel.setObjectName("nXLabel")
        self.gridLayout.addWidget(self.nXLabel, 0, 0, 1, 1)
        self.nXBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.nXBox.setMinimum(5)
        self.nXBox.setMaximum(100)
        self.nXBox.setProperty("value", 10)
        self.nXBox.setObjectName("nXBox")
        self.gridLayout.addWidget(self.nXBox, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.nYLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.nYLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.nYLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.nYLabel.setObjectName("nYLabel")
        self.gridLayout.addWidget(self.nYLabel, 1, 0, 1, 1)
        self.nYBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.nYBox.setMinimum(5)
        self.nYBox.setMaximum(100)
        self.nYBox.setProperty("value", 10)
        self.nYBox.setObjectName("nYBox")
        self.gridLayout.addWidget(self.nYBox, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.dimensionLabel = QtWidgets.QLabel(self.frame_4)
        self.dimensionLabel.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.dimensionLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.dimensionLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dimensionLabel.setTextFormat(QtCore.Qt.AutoText)
        self.dimensionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dimensionLabel.setObjectName("dimensionLabel")
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.mazeSelectLabel = QtWidgets.QLabel(self.frame_3)
        self.mazeSelectLabel.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.mazeSelectLabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.mazeSelectLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mazeSelectLabel.setLineWidth(2)
        self.mazeSelectLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mazeSelectLabel.setObjectName("mazeSelectLabel")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 40, 120, 103))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.randomButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.randomButton.setChecked(True)
        self.randomButton.setObjectName("randomButton")
        self.verticalLayout_2.addWidget(self.randomButton)
        self.primButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.primButton.setObjectName("primButton")
        self.verticalLayout_2.addWidget(self.primButton)
        self.kuzatsButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.kuzatsButton.setObjectName("kuzatsButton")
        self.verticalLayout_2.addWidget(self.kuzatsButton)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(mazeMenu)
        QtCore.QMetaObject.connectSlotsByName(mazeMenu)
        mazeMenu.setTabOrder(self.nXBox, self.nYBox)
        mazeMenu.setTabOrder(self.nYBox, self.randomButton)
        mazeMenu.setTabOrder(self.randomButton, self.primButton)
        mazeMenu.setTabOrder(self.primButton, self.kuzatsButton)
        mazeMenu.setTabOrder(self.kuzatsButton, self.drawButton)

    def retranslateUi(self, mazeMenu):
        _translate = QtCore.QCoreApplication.translate
        mazeMenu.setWindowTitle(_translate("mazeMenu", "Amazing Mazes"))
        self.drawButton.setToolTip(_translate("mazeMenu", "<html><head/><body><p>Create a random maze using the settings above.</p></body></html>"))
        self.drawButton.setText(_translate("mazeMenu", "Draw"))
        self.nXLabel.setText(_translate("mazeMenu", "N_x"))
        self.nXBox.setToolTip(_translate("mazeMenu", "<html><head/><body><p>Size of maze along x-axis.</p></body></html>"))
        self.nXBox.setSuffix(_translate("mazeMenu", " Cells"))
        self.nYLabel.setText(_translate("mazeMenu", "N_y"))
        self.nYBox.setToolTip(_translate("mazeMenu", "<html><head/><body><p>Size of maze along y-axis.</p></body></html>"))
        self.nYBox.setSuffix(_translate("mazeMenu", " Cells"))
        self.dimensionLabel.setText(_translate("mazeMenu", "Maze Dimensions"))
        self.mazeSelectLabel.setText(_translate("mazeMenu", "TextLabel"))
        self.randomButton.setText(_translate("mazeMenu", "Random"))
        self.primButton.setText(_translate("mazeMenu", "Prim"))
        self.kuzatsButton.setText(_translate("mazeMenu", "Kurzats"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mazeMenu = QtWidgets.QDialog()
    ui = Ui_mazeMenu()
    ui.setupUi(mazeMenu)
    mazeMenu.show()
    sys.exit(app.exec_())
